# -*- coding: utf-8 -*-
"""Resume_Maker_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIMKVS-WD5OKaZbLxvTVJG6_ONCWZz-S
"""

# Warning control
import warnings
warnings.filterwarnings('ignore')

!pip install crewai crewai-tools langchain-google-genai
!pip install "crewai[tools]" langchain-google-genai
from crewai import Agent, Task, Crew

import os
from google.colab import userdata
from crewai_tools import SerperDevTool, ScrapeWebsiteTool, FileReadTool

api_key = userdata.get('GEMINI_API_KEY')

# Set your Gemini API key from Google AI Studio
os.environ["GOOGLE_API_KEY"] = api_key

# Tell CrewAI to use Gemini globally as the default model
os.environ["MODEL"] = "gemini/gemini-2.5-flash"

# Initialize safe production tools
search_tool = SerperDevTool()
scrape_tool = ScrapeWebsiteTool()
read_resume = FileReadTool()  # Reads full text/raw LaTeX content from files instantly

import os
from google.colab import userdata
from crewai import Agent, LLM
from crewai_tools import SerperDevTool, ScrapeWebsiteTool, FileReadTool

# 1. Grab your secure key from Colab Secrets
api_key = userdata.get('GEMINI_API_KEY')

# 2. Force-feed BOTH global variables so every single underlying sub-library is happy
os.environ["GEMINI_API_KEY"] = api_key
os.environ["GOOGLE_API_KEY"] = api_key

# 3. Build a rock-solid native CrewAI LLM instance
gemini_llm = LLM(
    model="gemini/gemini-2.5-flash",
    api_key=api_key
)

job_researcher = Agent(
    role="Executive Technical Recruiter & Market Intelligence Analyst",
    goal="Deconstruct target job postings to identify latent hiring signals, non-negotiable hard tech stacks, core soft skill operational anchors, and organizational culture keywords.",
    backstory=(
        "You are a veteran technical recruiter with 15+ years of experience placing elite engineers. "
        "You don't just skim job descriptions; you reverse-engineer them. You can read a posting and immediately "
        "know exactly what architectural headaches the team is facing and what specific keywords the company's "
        "internal parsing software (ATS) is hard-coded to search for."
    ),
    tools=[scrape_tool, search_tool],
    llm=gemini_llm,
    allow_delegation=False,
    verbose=True
)

resume_strategist = Agent(
    role="Elite Executive Career Architect & Narrative Strategist",
    goal="Transform flat, task-oriented background profiles into high-impact, metrics-driven professional narratives that perfectly mirror corporate requirements.",
    backstory=(
        "You are a premier executive career coach who transforms basic resumes into elite marketing documents. "
        "You absolutely despise passive language (e.g., 'responsible for', 'assisted with'). You strictly employ the "
        "STAR framework (Situation, Task, Action, Result) and Google's X-Y-Z formula: 'Accomplished [X] as measured by [Y], "
        "by doing [Z]'. You know how to make raw experience look profoundly authoritative."
    ),
    tools=[read_resume],
    llm=gemini_llm,
    allow_delegation=False,
    verbose=True
)

ats_optimizer = Agent(
    role="ATS Systems Engineer & Linguistic Compliance Specialist",
    goal="Inject critical algorithmic keywords seamlessly into a resume narrative to maximize search visibility while preserving beautiful human readability.",
    backstory=(
        "You are an expert in algorithmic parsing, holding deep knowledge of platforms like Workday, Taleo, and Greenhouse. "
        "You understand that keyword stuffing gets a candidate rejected by human eyes, but missing semantic keywords gets "
        "them filtered out by the machine. Your genius lies in naturally weaving hard tech stacks and methodologies "
        "into normal sentences so that both bots and humans rate the resume as a 100% perfect match."
    ),
    llm=gemini_llm,
    allow_delegation=False,
    verbose=True
)

resume_formatter = Agent(
    role="Professional Typographer & Clean Markdown Document Designer",
    goal="Structure optimized unstructured text content into a stunning, executive-level, perfectly nested Markdown document.",
    backstory=(
        "You are a meticulous technical editor obsessed with layout hierarchy. You maintain perfect Markdown formatting rules, "
        "clean tables/grids where needed, and you NEVER overwrite or omit real identification headers like names, emails, or university names."
    ),
    tools=[],
    llm=gemini_llm,
    allow_delegation=False,
    verbose=True
)

# --- TASKS ---
from crewai import Task

task_analyze_job = Task(
    description=(
        "Analyze the targeted position provided in `job_input`: {job_input}\n\n"
        "ROUTING INSTRUCTION:\n"
        "1. Check if `job_input` is a website URL (starts with http:// or https://). If it is a link, execute ScrapeWebsiteTool to extract the text.\n"
        "2. If it is plain text, analyze it directly.\n"
        "3. If you need supplemental context regarding the company or their tech stack landscape, use SerperDevTool to query the web.\n\n"
        "Provide a comprehensive blueprint of the role: Extract the top 3-5 core technical requirements and the exact engineering problems they are trying to solve."
    ),
    expected_output="A concise technical requirements blueprint mapping hard tech stacks and core responsibilities.",
    agent=job_researcher
)

task_tailor_resume = Task(
    description=(
        "Review the candidate's raw text profile data provided in `profile_input`: {profile_input}\n\n"
        "CRITICAL ANTI-FLUFF & TRUTH INSTRUCTIONS:\n"
        "1. DO NOT hallucinate metrics. If a specific number or percentage does not exist in the raw text, do not invent it.\n"
        "2. Keep explanations strictly grounded in reality. Avoid empty filler words.\n"
        "3. Reconstruct passive experiences into impact-driven sentences using Google's X-Y-Z format.\n\n"
        "ROUTING INSTRUCTION:\n"
        "1. If `profile_input` points to a local file path, use FileReadTool to retrieve the text. Otherwise, analyze the text directly."
    ),
    expected_output="A grounded, high-impact professional resume draft aligned factually with the targeted role requirements.",
    agent=resume_strategist,
    context=[task_analyze_job]
)

task_ats_optimize = Task(
    description=(
        "Audit the tailored resume draft against the technical blueprint. Seamlessly integrate high-frequency keywords "
        "only where they make logical, grammatical sense. \n\n"
        "CRITICAL SKILLS GRID RULES:\n"
        "1. DO NOT include massive lists of technologies tagged as '(Conceptual)'. If the candidate hasn't actually used a tool or language in their experience/projects, REMOVE IT. A compact grid of true skills is vastly superior to a bloated list of tools they only read about once."
    ),
    expected_output="A linguistically compliant resume narrative optimized cleanly without keyword-stuffing or artificial bloat.",
    agent=ats_optimizer,
    context=[task_tailor_resume]
)

task_final_polish = Task(
    description=(
        "Take the optimized content and format it into a pristine, beautifully structured Markdown (.md) document.\n\n"
        "STRUCTURAL LAYOUT DESIGN:\n"
        "- Header block (Name, Contact Information, Links)\n"
        "- Professional Summary (Maximum 2-3 short, compelling sentences)\n"
        "- Core Technical Competencies (Clean layout grouping Languages, Libraries, Tools)\n"
        "- Professional Experience & Projects (Maximum 2-3 high-impact, short bullet points per item)\n"
        "- Education Section\n\n"
        "CRITICAL IMMUTABILITY RULE: You must preserve all real identifier tracking fields (Name, Contact Details, and explicit institutional markers like IIT Guwahati)."
    ),
    expected_output="A pristine, concise Markdown resume optimized for a clean, professional appearance.",
    agent=resume_formatter,
    context=[task_ats_optimize],
    output_file="tailored_resume_output.md"
)

# --- Inputs Setup (Hyper-Realistic, Comprehensive Raw LaTeX Profile) ---
inputs = {
    'job_input': """
    Machine Learning Engineer / Data Scientist (Energy & Optimization Focus)

    About the Role:
    We are seeking a technical Machine Learning Engineer to join our core systems optimization group.
    You will design, build, and deploy predictive models and bio-inspired optimization algorithms
    to maximize the efficiency of distributed renewable energy grids and large-scale industrial assets.

    Key Requirements:
    - Advanced proficiency in Python data science stacks (Pandas, NumPy, Scikit-Learn, SciPy).
    - Proven experience with predictive modeling, timeseries data analysis, and data visualization.
    - Familiarity with optimization frameworks, evolutionary/genetic algorithms, or heuristic search methods.
    - Experience building automated data pipelines and managing source code via Git/GitHub.
    - Strong mathematical foundation in linear algebra, statistics, and multivariate calculus.
    """,

    'profile_input': """
    Aarav Sharmendra
    Jaiput, Rajasthan, India
    Email: sharmendra678933.aarav@email.com | Phone: +91-9876543210
    GitHub: github.com/aaravsharmen678933 | LinkedIn: linkedin.com/in/aaravsharme696733

    EDUCATION
    Institute of Technology (IT), Rajkot (Jul 2023 -- Present)
    Bachelor of Technology (B.Tech) -- Engineering & Applied Sciences | CGPA: 8.42/10.0
    Relevant Coursework: Advanced Thermodynamics, Process Calculations, Machine Learning Foundations, Data Structures & Algorithms, Numerical Methods, Applied Statistics.

    PROFESSIONAL EXPERIENCE
    Nexus Energy Solutions | Bangalore, India (Remote)
    Data Science & Optimization Intern (May 2025 -- Jul 2025)
    - Worked with the core R&D team to handle massive timeseries datasets coming from solar panels and regional energy grids.
    - Responsible for writing Python scripts to clean messy input data, handle missing values, and remove sensor noise.
    - Assisted senior engineers in trying out different machine learning algorithms to predict power drops in the network.
    - Used libraries like Pandas and Scikit-Learn to evaluate model error rates and generated visualization reports for stakeholders.

    Department of Engineering, IT Rajkot | Rajkot, India
    Undergraduate Research Assistant (Jan 2025 -- Apr 2025)
    - Helped a professor analyze thermodynamic equilibrium datasets for complex mixture separations.
    - Wrote custom MATLAB and Python scripts to run iterative process calculations instead of doing them manually.
    - Gathered data from multiple research papers and organized it into a central database for open-source access.

    TECHNICAL PROJECTS
    Bio-Inspired Grid Optimization System (Python, SciPy, Matplotlib)
    - Built a simulation engine from scratch to look at renewable energy resource allocation across a simulated smart grid.
    - Implemented a genetic algorithm optimization routine to find the best tilt configurations for solar array placements.
    - Created beautiful data visualization tools using Matplotlib to show how energy waste dropped after applying the algorithm.
    - Saved a lot of computing time by vectorizing the calculations with NumPy arrays instead of using heavy for-loops.

    Climate Data Analytics & Visualization Tool (Python, Pandas, Seaborn, Git)
    - Developed an end-to-end data processing workflow to analyze multi-decade historical temperature fluctuations for major cities.
    - Wrote code to automatically clean anomalies and plot detailed monthly temperature boxplots to visualize long-term shifts.
    - Set up a structured GitHub repository containing documentation, a clean README, and reproducible Jupyter Notebook environments.

    TECHNICAL SKILLS
    - Languages: Python (Advanced), MATLAB, C++, SQL, LaTeX
    - Libraries & Frameworks: Pandas, NumPy, Scikit-Learn, SciPy, Seaborn, Matplotlib, Flask
    - Tools & Platforms: Git, GitHub, Linux, VS Code, Jupyter Notebooks, Docker (Basic)

    LEADERSHIP & ACHIEVEMENTS
    - Secured a position in the Top 5% of candidates nationwide in the highly competitive engineering entrance examinations.
    - Coordinated the graphic design and merchandising initiatives for the departmental student committee, managing custom apparel assets.
    - Active core member of the Public Health & Consumer Awareness group, drafting presentations on nutritional transparency and public health awareness for Indian markets.
    """
}

resume_crew = Crew(
    agents=[
        job_researcher,
        resume_strategist,
        ats_optimizer,
        resume_formatter
    ],
    tasks=[
        task_analyze_job,
        task_tailor_resume,
        task_ats_optimize,
        task_final_polish
    ],
    verbose=True
)

# Run the crew
final_output = await resume_crew.kickoff_async(inputs=inputs)

#Final Output
print(final_output)